### PR TITLE
[WIP] Please Add Needed Entities to `models/detects_alert.go`

### PR DESCRIPTION
**Pull request by kuma3ierae**
The file `models/detects_alert.go` used in `alerts.GetV2()` does not have some needed entities, for example Device entities.
I added these missing parts, based on `model/detects_behavior.go` and the following references:

* https://assets.falcon.us-2.crowdstrike.com/support/api/swagger-us2.html
* https://www.elastic.co/docs/current/integrations/crowdstrike#alert

### CODE REVIEW

**Comment by kuma3ierae** [comment]
I initially added some needed entities, such as Device, directly to `models/detects_alert.go` for `alerts.GetV2()`. However, I realized that this file is generated by Swagger, so direct modifications are not ideal. I apologize for the oversight.

I could not locate the original Swagger specification file used for generating this code. If possible, I would like to request a regeneration of this file with the needed entities added.

**Comment by ffalor** [comment]
Hey @kuma3ierae thank you very much for the time you spent on this. I've updated the `transformation.jq` file to add the missing fields and types based on the links you provided.

It will be included in the #456 pr. I plan on releasing it this week.

**Comment by kuma3ierae** [comment]
@ffalor 
thank you for updated by the #456.

**Comment by ffalor** [comment]
Hey @kuma3ierae  sorry for the delay. I've released `v0.9.0` 

The fields returned from the `alerts` endpoint are very dynamic and change depending on the type of alert that is thrown. I've done extensive testing and mapped all the fields I'm aware off. If you come across a field that is missing please let me know, and I'll make the necessary changes.

Thank you again for your help

**Pull request closed without merging**
