### PR TITLE
Fix the CI & sketch easy entry point & provide license & move aouth to middleware

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Review by shawndwells — CHANGES_REQUESTED** [review]
License text is not needed in individual files.

**Comment by isimluk** [comment]
Removed the license from all individual files as requested.

**Review by shawndwells — APPROVED** [review]
LICENSE changes approved. 

Punting to other team members for the Go code review.

**Comment by shawndwells** [comment]
+cc @jshcodes @jhseceng @redhatrises

**Pull request merged**
