### PR TITLE
Falcon Cleanup Hosts

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by redhatrises** [comment]
Just ran the script. Is there a way to say delete to the maximum of 100 hosts at one call vs deleting 1 by 1?

**Comment by isimluk** [comment]
Not at the moment, shouldn't be hard to add though.

**Comment by isimluk** [comment]
It is slow be design as a third layer of precaution.

**Comment by redhatrises** [comment]
> It is slow be design as a third layer of precaution.

Yeah... but will take quite a while to delete 1000s of hosts.

**Comment by isimluk** [comment]
Alright, will implement batching.

**Pull request merged**
